name: Install Terraform
description: Installs Terraform
runs:
  using: composite
  steps:
    - name: Install Terraform
      shell: bash
      run: bash ${{ github.action_path }}/install_terraform.sh